<?xml version="1.0"?>
<!--
  ArUco Visual Servoing - Differential Drive Robot URDF
  
  This file defines the complete kinematic and dynamic structure of a differential drive
  mobile robot equipped with an onboard camera for ArUco marker-based visual servoing.
  The model includes a base chassis, two independently actuated wheels, a caster wheel for
  stability, and a mounted camera with proper optical frame alignment.
  
  Robot Features:
  - Differential drive locomotion with independent left/right wheel control
  - Camera system with optical frame transformation
  - Caster wheel for stability on uneven surfaces
  - Complete inertial properties for physics simulation
  
  Author: Mohamed Eyad
  Date: December 13, 2025
  License: See package.xml for license information
-->

<robot name="aruco_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================================= -->
  <!-- External File Includes                    -->
  <!-- ========================================= -->
  
  <xacro:include filename="$(find arucobot_description)/urdf/aruco_bot_diff.gazebo.xacro"/>
  <xacro:include filename="$(find arucobot_description)/urdf/materials.xacro"/>

  <!-- ========================================= -->
  <!-- Robot Geometry Parameters                 -->
  <!-- ========================================= -->
  
  <xacro:property name="WHEEL_RADIUS" value="0.4"/>        <!-- meters -->
  <xacro:property name="WHEEL_WIDTH" value="0.2"/>         <!-- meters -->
  <xacro:property name="CASTER_RADIUS" value="0.2"/>       <!-- meters -->
  <xacro:property name="BASE_LENGTH" value="2.0"/>         <!-- meters -->
  <xacro:property name="BASE_WIDTH" value="1.0"/>          <!-- meters -->
  <xacro:property name="BASE_HEIGHT" value="0.5"/>         <!-- meters -->
  <xacro:property name="WHEEL_SEPARATION" value="${BASE_WIDTH + WHEEL_WIDTH}"/>
  
  <!-- ========================================= -->
  <!-- Robot Mass Properties                     -->
  <!-- ========================================= -->
  
  <xacro:property name="BASE_MASS" value="5.0"/>           <!-- kilograms -->
  <xacro:property name="WHEEL_MASS" value="2.0"/>          <!-- kilograms -->
  <xacro:property name="CASTER_MASS" value="1.0"/>         <!-- kilograms -->
  
  <!-- ========================================= -->
  <!-- Mathematical Constants                    -->
  <!-- ========================================= -->
  
  <xacro:property name="PI" value="3.14159265359"/>

  <!-- ========================================= -->
  <!-- Base Footprint and Chassis                -->
  <!-- ========================================= -->
  
  <link name="base_footprint"/>
  
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0 0" rpy="0 0 0.0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="${BASE_LENGTH} ${BASE_WIDTH} ${BASE_HEIGHT}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${BASE_MASS}"/>
      <inertia ixx="0.83333" ixy="0" ixz="0" iyy="1.66667" iyz="0" izz="1.66667"/>
    </inertial>
  </link>

  <!-- ========================================= -->
  <!-- Wheel Links                               -->
  <!-- ========================================= -->
  
  <!-- Left Wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${WHEEL_MASS}"/>
      <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_WIDTH}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${WHEEL_MASS}"/>
      <inertia ixx="0.145833" ixy="0" ixz="0" iyy="0.145833" iyz="0" izz="0.125"/>
    </inertial>
  </link>

  <!-- ========================================= -->
  <!-- Caster Wheel Link                         -->
  <!-- ========================================= -->
  
  <link name="caster">
    <visual>
      <geometry>
        <sphere radius="${CASTER_RADIUS}"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${CASTER_RADIUS}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${CASTER_MASS}"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- ========================================= -->
  <!-- Camera Links                              -->
  <!-- ========================================= -->
  
  <!-- Camera Physical Link -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.2 0.2 0.2"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.2 0.2 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>
  
  <!-- Camera Optical Frame (aligned with camera sensor coordinate system) -->
  <link name="camera_link_optical"/>

  <!-- ========================================= -->
  <!-- LiDAR Link                                -->
  <!-- ========================================= -->

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.002" ixy="0" ixz="0" iyy="0.002" iyz="0" izz="0.002"/>
    </inertial>
  </link>

  <!-- ========================================= -->
  <!-- Robot Joints                              -->
  <!-- ========================================= -->
  
  <!-- Left Wheel Joint (continuous rotation for locomotion) -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="-0.5 ${WHEEL_SEPARATION/2} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="10.0"/>
  </joint>

  <!-- Right Wheel Joint (continuous rotation for locomotion) -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="-0.5 -${WHEEL_SEPARATION/2} 0" rpy="-${PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="10.0"/>
  </joint>

  <!-- Caster Wheel Joint (fixed orientation, free to roll) -->
  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster"/>
    <origin xyz="0.8 0 -0.2" rpy="0 0 0"/>
  </joint>

  <!-- Camera Mounting Joint -->
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.9 0 0.36" rpy="0 0 0"/>
  </joint>

  <!-- Camera Optical Frame Transformation (ROS standard camera frame alignment) -->
  <joint type="fixed" name="camera_optical_joint">
    <origin xyz="0 0 0" rpy="-${PI/2} 0 -${PI/2}"/>
    <child link="camera_link_optical"/>
    <parent link="camera_link"/>
  </joint>

  <!-- LiDAR Joint -->
  <joint name="lidar_joint" type="fixed">
    <origin xyz="0.0 0.0 0.55" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="lidar_link"/>
  </joint>

</robot>